apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      name: bookstore
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: public.ecr.aws/v7c8v2n6/k8srepo:BUILD_ID
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
    k8s-app: bookstore
  name: bookstore
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: bookstore
